server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: Investment Dashboard
  
  # Fix path matching strategy issue
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  # Disable Thymeleaf since we're using static HTML
  thymeleaf:
    enabled: false
  
  # Static resources configuration
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 31536000 # 1 year cache for static resources
  
  # Security configuration
  security:
    user:
      name: admin
      password: admin
      roles: USER
  
  # Logging configuration
logging:
  level:
    com.investment: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Investment backend configuration
investment:
  backend:
    url: http://127.0.0.1:8000
    timeout: 30000
    
# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized